### ISSUE TITLE
mochify gobbles errors

### ISSUE THREAD

**Issue by boneskull** [mantoni/mochify.js#102]
when using mochify programmatically, this is a problem:

```js
  b.on('bundle', function (out) {
    out.on('error', error);
    out.pipe(opts.output);
  });
```

The caller of `mochify()` has a return value of `b`, but *doesn't* have access to the `out` variable, which means we can't grab any error it emits:

```js
var bundler = mochify(files);
bundler.on('error', function(e) {
  // this function is not called
});
bundler.bundle();
```

Proposal:

```js
  b.on('bundle', function (out) {
    out.on('error', function(err) {
      b.emit('error', err);
    });
    out.pipe(opts.output);
  });
```

**Comment by mantoni** [comment]
But couldn't you just listen on the `'bundle'` event to get the `out` reference and then listen on its `'error'`?

**Comment by boneskull** [comment]
indeed you are correct, though it's a bit circuitous.

anyway, I'm having some troubles here where the only output I receive is:

```
# phantomjs:
Error: Exit 1
```

So I'm trying to hunt down what's causing phantomjs (I assume) to die.

**Comment by mantoni** [comment]
Let me know your findings. Maybe we can improve the Mochify error handling.

**Comment by boneskull** [comment]
OK, so running `mochify` results in the above error.  But if I run:

```shell
$ browserify -p mocaccino ~/projects/decipher/angular-debaser/test/config.spec.js | phantomic --brout
```

I find out why my tests fail:

```
ReferenceError: Can't find variable: inject
    at http://localhost:60195/js/bundle:14
    at http://localhost:60195/js/bundle:30643
    at http://localhost:60195/js/bundle:164
    at http://localhost:60195/js/bundle:1
    at http://localhost:60195/js/bundle:1
    at http://localhost:60195/js/bundle:36263
1..0
# tests 0
# pass 0
# fail 0
```

**Comment by boneskull** [comment]
(correction; I'm not running `mochify` directly)

**Comment by boneskull** [comment]
hmm, but something on my site is actually eating the reporter output.  it doesn't seem to be mochify's fault.  thanks for your help.

**Comment by boneskull** [comment]
@mantoni alright, well, just ditched the API approach since Grunt is doing something untoward.  made [this](https://www.npmjs.com/package/grunt-mochify), if you're at all interested

**Comment by amchang** [comment]
Hey @boneskull how were you getting the output error? I am having the same issue where phantomjs is returning error code 1 and the error message is hidden from me, manually writing the browserify command like yourself.

**Comment by mantoni** [comment]
I'm guessing that this is a race condition, where the exit code is handled before all the ouput is consumed. I had this a few times and Phantomic explicitly deals with this. But like I said, just a guess.

@boneskull Thanks for putting a Grunt task together. Shall we add a link on the Mochify readme?
