### ISSUE TITLE
default mocha reporter is now "spec"

### ISSUE THREAD

**Issue by boneskull** [mantoni/mochify.js#104]
not sure if you want to change it, or just eliminate the default and let mocha decide

**Comment by mantoni** [comment]
Makes sense to eliminate and let Mocha decide. This is a leftover from Mocha's decision to change the default reporter in a minor release. It was aligned before...

**Comment by boneskull** [comment]
> This is a leftover from Mocha's decision to change the default reporter in a minor release

ugh, don't remind me. live & learn...

**Comment by mantoni** [comment]
Fixed in `v3.0.0`.
