### ISSUE TITLE
Can't get listen for error result during tests when using mochify with gulp

### ISSUE THREAD

**Issue by bitwit** [mantoni/mochify.js#108]
Hi, I'm in the process of writing a gulp build process that runs mochify. So far it working perfectly except for the fact that I get an Exit code of 0 regardless of whether the tests pass or not.

When using `.on('error')` I don't get any output from the bundle if it's spawned phantom process fails.

Looking at this line https://github.com/mantoni/mochify.js/blob/master/lib/mochify.js#L78 I believe something needs to be done here to emit a message but my efforts to find a solution have been fruitless. For example, throwing an error from that line prevents the reporter output from ever showing (which would mean I can't see where something went wrong) so that's not the right answer.

For thoroughness here is my gulp build code:
```
gulp.task('testCore', function () {
        var fileNames = [];
        return  gulp.src([
                src.core + '/**/**.spec.js'
        ])
        .pipe(through.obj(function (file, enc, next) {
                var path = file.path.replace(__dirname, '.');
                fileNames.push(path);
                next();
        }, function (next) {
                mochify(fileNames.join(' '), {
                        reporter: 'spec',
                })
                .plugin('proxyquire-universal')
                .plugin('mochify-istanbul', {
                        report: 'html',
                        dir: './test/core/coverage'
                })
                .bundle()
                .on('error', function (err) {
                        console.log('ERROR!');
                        next(err);
                })
                .on('end', function () {
                        next();
                });
        }));
});
```

the 'error' is never called, but the 'end' event works as expected.

**Comment by mantoni** [comment]
Hm. I can't really look into that currently, but try passing a function to `bundle` that receives `(err, output)` and see whether that gives you better results.

**Comment by bitwit** [comment]
Just got it!

`.bundle` should have gone at the VERY bottom after the 'on' listeners and everything worked.

```
 mochify(fileNames.join(' '), {
                        reporter: 'spec',
                })
                .plugin('proxyquire-universal')
                .plugin('mochify-istanbul', {
                        report: 'html',
                        dir: './test/core/coverage'
                })
                .on('error', function (err) {
                        next(err);
                })
                .on('end', function () {
                        next();
                })
                .bundle(); // bundle at the VERY end after listeners
```

Looking at the phantom module code in the project hinted to me that running the tests is part of the browserify bundle process rather than occurring after it.

I always tried your suggested way for thoroughness with passing a function directly into `.bundle` that didn't work. The err came back as null.

**Comment by bitwit** [comment]
(p.s. thank you for the fast reply!)
