### ISSUE TITLE
Large scripts don't run on Chorme

### ISSUE THREAD

**Issue by gnandretta** [mantoni/mochify.js#110]
I'm using mochify.js to test an application that uses react.js and immutable.js. When running test on Chrome via Selenium I got the error below (works fine on Firefox).

I've created a [repository](https://github.com/gnandretta/mochify-react-example) with a minimal example to reproduce the issue. 

```
$ npm run test

> hello-react@1.0.0 test /Users/gnandretta/Code/mochify-react-example
> mochify --wd

# firefox *:


  ..

  2 passing (27ms)


# chrome *:
POST /wd/hub/session/a204ee59-0ed7-42e1-b864-2640c03729cd/execute

Unexpected HTTP status: 500 Internal Server Error

date: Wed, 12 Aug 2015 00:20:04 GMT
server: Jetty/5.1.x (Mac OS X/10.10.4 x86_64 java/1.8.0_51
expires: Thu, 01 Jan 1970 00:00:00 GMT, Thu, 01 Jan 1970 00:00:00 GMT
cache-control: no-cache, no-cache
content-length: 305065
content-type: application/json; charset=utf-8

Response Status Code: 13
Response Message:
    disconnected: Unable to receive message from renderer
      (Session info: chrome=44.0.2403.155)
      (Driver info: chromedriver=2.17.340128 (994135a3538dd99439ef22cea8a9b098e00d8eb4),platform=Mac OS X 10.10.4 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 104 milliseconds
    Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
    System info: host: 'Gabriels-MacBook-Pro.local', ip: '192.168.0.101', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.4', java.version: '1.8.0_51'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/h_/08605f3j0s9d7ffrtb5shbvh0000gn/T/.org.chromium.Chromium.BzBjH5}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=44.0.2403.155, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 6d054d2292c24ec5649fd721ae8dd2d2
```

**Comment by mantoni** [comment]
Thanks for reporting. You can try to increase the memory limit for the selenium process:

```
$ java -jar -Xmx1024M ...
```

**Comment by gnandretta** [comment]
Thanks for answering.

The problem still occurs when increasing the memory limit.

**Comment by mantoni** [comment]
Sorry, I finally found some time to look into this, unfortunately without any solution.

I can reproduce now using your provided project (thanks again) using latest Chrome, Java, Selenium Standalone and Chromedriver. Anyones help on this is greatly appreciated.

**Comment by mantoni** [comment]
Others are reporting the same here: https://bugs.chromium.org/p/chromedriver/issues/detail?id=402
Apparently, this is a bug that was solved and is now occurring again.

**Comment by mantoni** [comment]
I'm sorry this was an open issue for such a long time. Fortunately I managed to narrow down the issue and provide a workaround in [min-webdriver 2.9.1](https://github.com/mantoni/min-webdriver/blob/master/CHANGES.md#291).

There is no need to change anything in Mochify itself. Just update your dependencies and it should be fixed.

Please open a new issue or comment here if it's still not working.

**Comment by gnandretta** [comment]
It works, thank you!
