### ISSUE TITLE
Report colours

### ISSUE THREAD

**Issue by polvoblanco** [mantoni/mochify.js#112]
How do you modify the report colours?

I use the Solarized theme in my terminal (urxvt) and the report colour 90 is the exact same colour as the background, so any text that is this colour is invisible.  This appears to be a very common problem and has quite a bit of coverage on the mocha issues pages.  I have found the easiest way to fix this is to simply require colors from mocha/lib/reporters/base and change any colours set to 90 to 92 (or whatever) at the start of the tests.  However, when using mochify, this hack does not work. Can you let me know how I need to modify this hack to make it work with mochify?

Thanks.

**Comment by mantoni** [comment]
The `Mocha` global is available in Mochify. This allows you to modify `Mocha.reporters.Base.colors`.

Alternatively, you can disable color entirely with `----no-colors` on the command line, or `{ colors : false }` in the API.

**Comment by polvoblanco** [comment]
That was easy, thanks.
