### ISSUE TITLE
Mochify is omiting Unicode chars in its reports 

### ISSUE THREAD

**Issue by borodean** [mantoni/mochify.js#113]
Test case, notice the euro sign in the expected value:
```js
describe('foo', function () {
  it('bars', function () {
    expect('baz').to.equal('100€');
  });
});
```

Mochify's output:
```
1) foo bars:

    AssertionError: expected 'baz' to equal '100'
    + expected - actual

    +100
    -baz
```

The euro sign is omitted from the `100€` part of the report. I've tried the same thing with Ukrainian letters which are obviosly Unicode as well and they are also getting omitted.

I've ran the similar tests on bare Mocha, and there all these characters are being output fine.

**Comment by mantoni** [comment]
I tried to reproduce with a test case here with no luck (c82366b7c55f219a7fe4bdb0eaab25932e4410e8). But the travis build on node 0.10 failed.

Which node version are you using? Can you run `mochify test/fixture/unicode/test/unicode.js` in the mochify directory to check the output in your environment?

**Comment by borodean** [comment]
@mantoni it fails. I have node v0.12.7.

**Comment by mantoni** [comment]
@borodean Of cause it fails, it's a failing test case comparing the euro unicode sign with the number three :smile: But what does it print on your screen? Does it show the unicode character properly?

**Comment by mantoni** [comment]
@borodean Do you still have this issue? Can you help reproduce? It's working as expected on my end.

**Comment by mantoni** [comment]
If anyone can describe how to reproduce, I'm happy to reopen.
