### ISSUE TITLE
missing variables from a browser context

### ISSUE THREAD

**Issue by nickdesaulniers** [mantoni/mochify.js#114]
Forgive me if I'm mistaken.  I'm trying to test out some WebGL modules I'm building with Browserify.  I figured that mochify.js runs things in a headless brower, so variables attached to the window object would be accessible.  When I run my tests with mochify.js, this doesn't seem to be the case:
```
➜  compile-shader git:(master) ✗ ./node_modules/mochify/bin/cmd.js -R nyan
# phantomjs:
 0   -_-_,------,
 2   -_-_|   /\_/\
 0   -_-^|__( x .x)
     -_-  ""  ""

  0 passing (11ms)
  2 failing

  1) Bad Input bad type should throw:
     Can't find variable: WebGLRenderingContext
      at exports (test/compiled.js:5:37)
      at test/compiled.js:33:20

  2) Bad Input bad type should throw:
     Can't find variable: WebGLRenderingContext
      at exports (index.js:4:37)
      at test/tests.js:6:20



Error: Exit 1
```
Note: WebGLRenderingContext is a member of the window object.  This module loads fine in a non-headless-browser after being built with browserify.  What am I doing wrong?

**Comment by boneskull** [comment]
No WebGL support in [PhantomJS](http://phantomjs.org/), I'd imagine.

**Comment by nickdesaulniers** [comment]
[ack!](http://phantomjs.org/supported-web-standards.html) thanks
