### ISSUE TITLE
Test while requiring from multiple bundles

### ISSUE THREAD

**Issue by lsapan** [mantoni/mochify.js#118]
Our compile step would normally take about 10 seconds due to the size of libraries we use in our application. To shorten this, we separated our code from our library code into `main.built.js` and `libs.built.js`.

However, when we run mochify, we haven't found a way to run our tests without throwing everything into one giant bundle. Is there a similar way to tell mochify to "include" `libs.built.js`?

**Comment by mantoni** [comment]
Did you already try `--require ./libs.built.js`?

**Comment by lsapan** [comment]
I did from the API, but it seemed to do some weird stuff where it was just trying to find files in the same folder as libs.built.js.

**Comment by mantoni** [comment]
That sounds like you added it to the argument list. What I mean is passing it in the options. Otherwise, adding additional libraries to the bundle should be easy to add.

**Comment by lsapan** [comment]
Maybe I'm misunderstanding, but I'm fairly sure I'm adding it in the proper place. Here's where I'm doing it:

```
var b = mochify(__dirname + '/test/tests.js', {
    require: __dirname + '/main/static/build/libs.built.js',
});

b.plugin(istanbul, ...) //shortened for brevity

b.bundle();
```

**Comment by mantoni** [comment]
Thanks for the code snipped. I guess `require` will only work with module names. You can try using [browserify's add method](https://github.com/substack/node-browserify#baddfile-opts) instead:

```js
var b = mochify(__dirname + '/test/tests.js');
b.add(__dirname + '/main/static/build/libs.built.js');
// ...
b.bundle();
```

If that solves the issue, we could possibly think about adding `add` as a Mochify option.

**Comment by lsapan** [comment]
Oddly enough that yields the same result :\

**Comment by mantoni** [comment]
Hmm, I'd guess that your `libs.built.js` would need to be added before the test cases. Did you already try this?

```js
var b = mochify(__dirname + '/main/static/build/libs.built.js ' + __dirname + '/test/tests.js');
// ...
```

**Comment by mantoni** [comment]
Closing. Please reopen if you tried my latest suggestion and it still doesn't work.
