### ISSUE TITLE
How do I test code that uses jquery if it is hosted by google when in production?

### ISSUE THREAD

**Issue by priedthirdeye** [mantoni/mochify.js#119]
I figured out how to include jquery in tests (which does not result in it being included in the final production js file)

I'd like to use jquery in my actual production code and test it without having jquery included in my final production file. We typically have our jquery served from google.

![code](https://cloud.githubusercontent.com/assets/5795993/11133986/73405b78-8967-11e5-90bb-31a3657dfc99.png)

I'm pretty new server side javascript in general. Perhaps an alias will allow me to accomplish my goal?

**Comment by mantoni** [comment]
You can simply use jQuery everywhere and just exclude it from the Browserify bundle. I don't really understand how Mochify can help?

**Comment by priedthirdeye** [comment]
When I exclude jquery from browserify bundle both tests fail

  "browser": {
    "jquery": false
  }

Question Restated:

Is it possible to include a library such as jquery for testing, but exclude it from the build since it will ultimately be hosted by a third party?

---
Apologies for my lack of experience with this type of workflow and possibly a stupid question.

**Comment by priedthirdeye** [comment]
I'm starting to think that that answer is "no" and that I should reconsider serving jquery from google for the page/application that I'm working on. 

The downside is that the library would already be in cache from visiting my site but would ultimately need to download it again in my bundle.

**Comment by priedthirdeye** [comment]
..Or maybe I include jquery for development but exclude it for production.

Keep in mind I'm jumping from writing in mostly inline spaghetti-code javascript to this (node/browserify/mocha/grunt) workflow. 

Any insight is appreciated.

**Comment by mantoni** [comment]
I think I understand the problem now. One option could be to try and remove excludes from the Browserify instance in Mochify. But I fear there is no API for that :-/

**Comment by mantoni** [comment]
I think you should try and solve this with [browserify-shim](https://www.npmjs.com/package/browserify-shim). If you find out anything specific that Mochify can do, please feel free to add comments here or open a new issue.
