### ISSUE TITLE
CORS rejected

### ISSUE THREAD

**Issue by arve0** [mantoni/mochify.js#121]
Hi!
Both `mochify` and `mochify --web-security=false` gives me CORS errors. The same tests pass with [consolify](https://github.com/mantoni/consolify) in Chrome.

PhanomJS version: 1.9.8

Replicate:
```sh
git clone https://github.com/arve0/node-google-spreadsheets
cd node-google-spreadsheets
git checkout -b mochify origin/mochify
npm install
npm test
```

Output:
```sh
  1) google-spreadsheets can load a spreadsheet:
     CORS request rejected: https://spreadsheets.google.com/feeds/worksheets/0ApDvWFF4RPZBdEFucnJya1hxVG9wZzhJQWZUWkpfekE/public/values?alt=json
```

This is an error code from [browser-request line 242](https://github.com/iriscouch/browser-request/blob/master/index.js#L242). Using [request](https://github.com/request/request) I get the same error, with a slightly different message: `XHR error`.

[A tiny test-HTML](https://github.com/arve0/node-google-spreadsheets/blob/mochify/test/index.html) is included in the test directory, which can be opened in browser from filesystem after a `npm run build` (browserifies the library).

**Comment by mantoni** [comment]
Thanks for all the detailed information.
Before I start to dig in, have you tried `--web-security false --ignore-ssl-errors`?

**Comment by arve0** [comment]
No I haven't tried that. It crossed my mind, but went away. I'll give it a try later today.

**Comment by arve0** [comment]
`--ignore-ssl-errors` resolves it.
