### ISSUE TITLE
Changing the timezone for tests

### ISSUE THREAD

**Issue by fabioel** [mantoni/mochify.js#125]
I have a problem changing the timezone for phantomjs when using mochify.
The normal way to change the timezone in phantom is as follow:

`TZ='America/Los_Angeles' phantomjs`

I tested this and it works when I use phantom on its own:

    echo "console.log(new Date)" | TZ=America/Los_Angeles phantomjs
    phantomjs> Fri Jan 08 2016 03:15:05 GMT-0800 (PST)

but as soon as I use `mochify` I can neither access the system variable `$TZ` nor can I set the TZ of phantomjs

is there a possibility to set the timezone of `phantomjs` when using `mochify`?

**Comment by fabioel** [comment]
i fixed this in the pull request https://github.com/mantoni/phantomic/pull/11

**Comment by fabioel** [comment]
@mantoni can you please update the `package.json` with the current version of phantomic?

**Comment by mantoni** [comment]
It will install automatically due to the `^` range. Just re-install Mochify.

**Comment by fabioel** [comment]
ok I was not sure :smile:
