### ISSUE TITLE
Allow passing an --wd-min-file flag

### ISSUE THREAD

**Issue by kolodny** [mantoni/mochify.js#127]
For local development I want to test in FF and Chrome but in travis CI I want to use IE's and whatnot

**Comment by mantoni** [comment]
I would certainly support any effort in getting this feature in. Should be an easy one.

**Comment by kolodny** [comment]
This will be reliant on a change in wd-min, correct?

**Comment by mantoni** [comment]
Yes, that is correct. You'd have to add the feature there and integrate here by passing the option through. There are a couple of options passed from Mochify to min-wd already, so you can see how that works.

**Comment by kolodny** [comment]
PR here: #131

**Comment by mantoni** [comment]
Feature released in `2.16.0`. Closing.
