### ISSUE TITLE
Update Mocha dep to 3.x

### ISSUE THREAD

**Issue by wesleytodd** [mantoni/mochify.js#142]
I can submit a PR for this, but is it just a matter of updating the `package.json`?

**Comment by mantoni** [comment]
Yes and no. Since it is a major release I also wanted to put some other potential breaking changes into a release with Mocha 3. Didn't get to it yet …

**Comment by wesleytodd** [comment]
Ah, I figured it wouldn't be that simple.  How soon and is there anything that I can help with?

**Comment by mantoni** [comment]
If you want to help, that'd be awesome! There are three things to work on, so let's make a checklist 🏁 

- [ ] __Easy__ The default reporter should be taken from Mocha. It's currently hard-wired to be the "dot" reporter. Mocha itself changed the default to "spec". Mochify should use whatever the default in Mocha is.
- [ ] __Medium__ I know that Mocha is easier to browserify now and maybe things can be simplified in `mocaccino`.
- [ ] __Advanced__ If you look at the `consolify` and the `min-webdriver` integrations, they're pretty much only browserify plugins now. I would like to make them entirely optional. If this is too difficult or can only be achieved with one of them easily, that's also fine.

Once these are investigated and/or addressed, I'll bump Mocha and release a new major 📦

**Comment by mantoni** [comment]
Mochify `v3.0.0` has been released today with Mocha 3 and Browserify 14. 🎉
