### ISSUE TITLE
Support mocha's --reporter-options option?

### ISSUE THREAD

**Issue by Melatonin64** [mantoni/mochify.js#143]
Is there a way to pass a `--reporter-options` value to [mocha](https://mochajs.org/#usage)?
I'm using the programmatic API in case that matters...
Thanks!

**Comment by mantoni** [comment]
No, this is not supported (yet).

If you want to take a look at it, this needs a [new feature in mocaccion](https://github.com/mantoni/mocaccino.js) and then adding a [new option here](https://github.com/mantoni/mochify.js/blob/1f8fac6eb74031d0eec8977099d7080db3b7bf0e/lib/mochify.js#L115).
