### ISSUE TITLE
Tests fail without report when using `mochify-istanbul`

### ISSUE THREAD

**Issue by m90** [mantoni/mochify.js#146]
I'm running a test suite against mochify. When starting to add coverage reports using `mochify-istanbul` I am facing the following issue:

When one of the tests fails I will not see the report, but simply:

```
# phantomjs:
Error: Exit 1
```

which makes it rather hard to find out what broke.

My test command looks like:

```
"mochify": "NODE_ENV=test mochify --plugin [ mochify-istanbul --report html --dir ./js_coverage --exclude '**/*.{json,toml,html,test.js}' ] --timeout=10000 --reporter=spec ./assets/scripts/test/unit/**/*.js",
```

When no tests fail, the report will be printed all at once. Is there any way to work around this behavior?

**Comment by mantoni** [comment]
You can try to use `--debug` to run the debugger.

**Comment by m90** [comment]
Interestingly, when I use the `--debug` flag and kick off the tests manually in the sources panel it will work as expected (as in I will see what failed), but I will also see a note on how phantomjs has crashed (which is probably causing the initially described behavior):

```
  116 passing (6s)
  1 failing

  1) components/filter-bar FilterBarComponent initializes model, view and sets its el:

      BOOM
      + expected - actual

      -false
      +true
      
      fail node_modules/assert/assert.js:201
      ok node_modules/assert/assert.js:215
      assets/scripts/test/unit/components/filter-bar.test.js:41



PhantomJS has crashed. Please read the bug reporting guide at
<http://phantomjs.org/bug-reporting.html> and file a bug report.
```

**Comment by mantoni** [comment]
No, I think if you're using `--debug` then PhantomJS always crashes. It's not really shutting down cleanly in this case, so I think it's not related.

**Comment by m90** [comment]
Would it help if I'd create an example repo for reproducing this issue?

**Comment by mantoni** [comment]
TBH I don't know where to look either and I currently have little time to investigate. Here are two things you can work with:

- Try using `--consolify` and run the generated file in a real browser
- Try to create the pipeline yourself as described in the <https://github.com/mantoni/mocaccino.js> readme and do not use the `--brout` option (alternatively search for the option in the mochify sources and disable it).

**Comment by m90** [comment]
This should hopefully be fixed via: https://github.com/ferlores/mochify-istanbul/pull/24
