### ISSUE TITLE
Use Chrome headless

### ISSUE THREAD

**Issue by fatso83** [mantoni/mochify.js#159]
Wouldn't the [Puppeteer API](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md) be enough to create a 'chromific' version of phantomic that could replace phantomic? I think capturing the streamed data as a string, opening a browser.newPage() and running browser.evaluate() on the captured data would basically be sufficient. Might be a bit simplistic, of course...

**Comment by mantoni** [comment]
Yes, that might work. I was having the same thought, but am quite busy atm. Do you have time to look into it?

**Comment by m90** [comment]
I actually tried creating a Headless Chrome version of Phantomic when Headless came out (like 3 months ago or so using the ChromeLauncher that ships with Lighthouse) and gave up as I wasn't able to detect test end like it is done in phantomic (which from what I understand relies on Phantom being slowish, The delta in Chrome was always 100, no matter how many tests were running): https://github.com/mantoni/phantomic/blob/master/lib/page.html#L35-L44

Would this be easier in a Pupeteer context?

**Comment by mantoni** [comment]
I've put an initial Chromium based implementation in the [chromium](https://github.com/mantoni/mochify.js/tree/chromium) branch. It's a bit hacky, but it works, also with watch mode.

Outstanding work:

- [ ] `executablePath` path option to launch a custom install
- [ ] Make sure the `--debug` is usable and document how to
- [ ] Try to block navigation somehow. Maybe with event listeners that `preventDefault` or the like. There is a flag for PhantomJS, but this feature is not supported by Puppeteer.
- [ ] Deprecate Node 4 as Puppeteer requires Node 6
- [ ] Change descriptions and compatility notes in README.

**Comment by mantoni** [comment]
On second though, I made it a [pull request](https://github.com/mantoni/mochify.js/pull/161) for easier collaboration.

**Comment by mantoni** [comment]
#161 landed and released in `v5.0.0` 🚀
