### ISSUE TITLE
Option to pass additional arguments to chrome

### ISSUE THREAD

**Issue by fearphage** [mantoni/mochify.js#162]
I'm running mochify as the root user in docker. Chrome needs [special flags](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-fails-due-to-sandbox-issues) to allow it to run as root. It would be convenient if I could pass those in myself. 

I was picturing this taking one of two forms:

* `--chrome-as-root` (or a similar flag) - adds the two needed flags
* `--chrome-args [ insert flags here]` - allows adding of arbitrary flags

**Comment by mantoni** [comment]
Thanks for looking into this. Great help 👍 

Maybe we could as well add those `args` by default. I don't see how they're causing any problems in the context of a test runner. What do you think?

**Comment by fearphage** [comment]
There are security implications. I don't believe you want these to be default options. They should be opt-in.
