### ISSUE TITLE
Use random port if no port is specified

### ISSUE THREAD

**Issue by mantoni** [mantoni/mochify.js#164]
The `--https-server` option currently takes the port number where to open the HTTPS server. If no port number is given, Mochify should use a random free port. This is only possible if _no_ `--url` is given, or the URL must be parsed, the port number changed and the URL recreated with the random port.

The relevant code block is this one:

https://github.com/mantoni/mochify.js/blob/fd0c6b520caf0ade87289d66f111ef6a6f8f75fb/lib/chromium.js#L160-L191

See https://github.com/sinonjs/sinon/issues/1643

**Comment by m90** [comment]
As per #168 passing no value to `--https-server` will now make mochify pick a random free port.

This still does not solve the situation where the user passes both `--https-server` **and** `--url`. Ideally the following would happen

> When specifying both, the --url and the --https-server options, it was / is the users responsibility to configure matching ports in both cases. This can stay as is for now. You'd basically have to specify the port that you're using in --url or it won't work.
>
> What would be awsome though, is if the automatic port feature could work with --url as well. I can imagine this working like this: We parse the --url for a port number and launch the server on the matching port. If the port is 0 (e.g. https://localhost:0/foo), we let the OS find a free port and change the URL to point to that port.

**Comment by mantoni** [comment]
Support for random port selection if no port is given in `--https-server` was released in `v5.4.0`.

**Comment by m90** [comment]
Closed via #169 and published to npm at `v.5.0`
