### ISSUE TITLE
Cannot set viewport

### ISSUE THREAD

**Issue by VinhVu0412** [mantoni/mochify.js#166]
I run mochify with a command likes this `mochify --viewport-height 2000 --viewport-width 2000` and it comes with an error message `(node:65342) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol error (Emulation.setDeviceMetricsOverride): Invalid parameters width: integer value expected; height: integer value expected`

It was ok when I used mochify 3.3.0. The error came when I upgraded to 5.2.0 

I am using 
- mochify 5.20
- node 6.10.3
- mocha 4.1
- browserify 15.2
- puppeteer 1.0

**Comment by m90** [comment]
It looks like these values: https://github.com/mantoni/mochify.js/blob/ed471aceb81d66a21aa53819bcab656c84f0ad0c/lib/chromium.js#L84-L85 are actually strings when they should be ints. The [tests](https://github.com/mantoni/mochify.js/blob/ed471aceb81d66a21aa53819bcab656c84f0ad0c/test/args-test.js#L143-L151) only check for `equal`, so I would assume the args parser does not really do what we want it to.

I can look into fixing this if @mantoni  does not mind.

**Comment by mantoni** [comment]
@m90 Sure, go ahead! I assume that phantomjs used to work fine with strings and headless chrome doesn't.

**Comment by m90** [comment]
@VinhVu0412 This is fixed as of `5.3.1` which is now published to npm.
