### ISSUE TITLE
Pass flags to Browserify

### ISSUE THREAD

**Issue by fatso83** [mantoni/mochify.js#208]
I don't see any way of passing Browserify flags on the `mochify` command line. What I do see from the mochify docs is this:

> The mochify function returns a Browserify instance. Please refer to the Browserify API for details.

I take it that means that any custom configuration of Browserify means using the javascript CLI? There's no `.mochify.config` or similar? I also assume it means that the returned browserify instance can be configured using additional opts?

Pingback sinonjs/sinon#2085

**Comment by mantoni** [comment]
There is support for quite a few Browserify options. However, they have to be enabled on a case by case basis, becaue we also support a variety of Mocha options, and there can be name clashes, especially in the shorthand versions. Mochify is truly a hybrid of Mocha and Browserify.

The referenced Sinon issue will be addressed by #209. Please let me know if there are other specific options that you would like to have.

**Comment by fatso83** [comment]
I don't know of any explicit other options, atm, unfortunately. This is basically to support the Sinon tests using mochify.

**Comment by mantoni** [comment]
Closing since the original motivation for this issue was addressed. More issues for specific flags / features welcome 👍
