### ISSUE TITLE
Rewrite: Puppeteer settings

### ISSUE THREAD

**Issue by mantoni** [mantoni/mochify.js#245]
Following up on #243, we need to allow custom chrome binaries and custom puppeteer settings.

We could provide sensible default settings for the testing scenario and then allow users to override those settings with any options they want.

For the custom chrome binary, this was the previous implementation:

```js
  if (opts.chrome) {
    options.executablePath = opts.chrome;
  } else if (process.env.PUPPETEER_EXECUTABLE_PATH) {
    // Workaround for https://github.com/puppeteer/puppeteer/issues/6957
    options.executablePath = process.env.PUPPETEER_EXECUTABLE_PATH;
  }
```

**Comment by m90** [comment]
I can take care of this this week (as if affects me too).
