### ISSUE TITLE
Rewrite: Implement watch mode

### ISSUE THREAD

**Issue by mantoni** [mantoni/mochify.js#247]
`mochify --watch` should behave the same way as `mocha --watch`.

**Comment by itayperry** [comment]
Hi @mantoni, I can see that the milestone issues are being handled at the **speed of light**! This is very exciting :) 

Can I help? Is this issue ok to start with for "beginners"? If so, just tell me where to start! 
(even though I understand that until I'll implement it you might already close it yourself lol).

**Comment by mantoni** [comment]
I'm not sure whether this is for beginners or not. The previous implementation was using `watchify`, but we're moving away from direct bundler dependencies.

I guess I'd start by looking into how mocha does it …

Thank you for picking this up ❤️

**Comment by m90** [comment]
Just out of curiosity (and because I don't know how to answer this myself): would watch mode be a feature of `@mochify/mochify` (i.e. the API module) or would that be a CLI only thing?

**Comment by mantoni** [comment]
Since file globs are resolved in the API, I guess it will naturally happen there, no?

**Comment by itayperry** [comment]
Hi, it takes time to understand everything, but I can see that both `mocha` and `watchify` use `chokidar` to watch files - this seems to be the heart of the process. I'm still looking into this :)
https://github.com/mochajs/mocha/blob/a87461caf23999a8b0a64b5f46486b53900a8461/lib/cli/watch-run.js#L170-L173

**Comment by itayperry** [comment]
Hi @mantoni, I have some silly 'juniorish' questions - I looked at some old commits - really old lol https://github.com/mantoni/mochify.js/commit/1348b92c14cd370002b94bda4196e5272aa2cd13
To use `mochify` (**old and new upcoming version**) do I have to bundle my code **only** with `browserify`? 
And if that is true.. is this issue about building our own new `watchify` ?

> we're moving away from direct bundler dependencies

to reduce repository size?

**Comment by mantoni** [comment]
This does the trick for now:

```bash
chokidar '**/*.js' -c 'npm t' --initial --silent
```

If anyone wants to include that into the mochfiy implementation, development has moved here:
https://github.com/mochify-js
