### ISSUE TITLE
Depend on the `phantomjs` module

### ISSUE THREAD

**Issue by sindresorhus** [mantoni/mochify.js#28]
So users don't have to install PhantomJS manually.

https://github.com/Medium/phantomjs

**Comment by lukasoppermann** [comment]
Can you please add this to the dependencies? It is really annoying, I tend to forget to install it and it is not really nice, to have deps in your package.json that are actually deps of a package and not your main project.

**Comment by mantoni** [comment]
The last time I checked, the npm dependency did not recognize my global install and would download the whole phantomjs thing on each fresh install. This is why I've decided to just print a message explaining what to do.
