### ISSUE TITLE
#featureRequest browserSync integration

### ISSUE THREAD

**Issue by rstormsf** [mantoni/mochify.js#46]
Would be great if it can be used with BrowserSync to serve the local folder with tests 
The same way PhantomJS does it, but its chromedevtools is outdated and in my case, after each test it's crashing(see #45 )

I will see how I can do it myself as well, Will PR if I get it done
BrowserSync can fire localhost and specify the folder to serve.
It only makes sense to integrate it on watch, so people can move to sources and start debugging code there

**Comment by mantoni** [comment]
With `v2.8.0` you can generate a separate bundle.js file:

```
mochify --consolify test.html --bundle test-bundle.js
```

This way you get proper source maps and it should enable you to come up with a BrowserSync setup.
You can also combine this with `--watch`.

Please let me know how far this gets you.

**Comment by mantoni** [comment]
There will be no direct BrowserSync integration. There is a solution now that should make it easier to combine both tools. If there are more ideas, please file a new issue. Thanks for your patience.
