### ISSUE TITLE
Updating from 0.11.3 to >1.0.0 I get missing module errors

### ISSUE THREAD

**Issue by glassresistor** [mantoni/mochify.js#51]
It works until I upgrade to 1.0.0.  Its failing on the first require in the test directory.  It imports stuff out of main code and libraries fine.

```
# phantomjs:
Error: Cannot find module './utils'
    at test/ad.js:7
    at null:null


  0 passing (1ms)

Error: Exit 1

**Comment by mantoni** [comment]
Is this still a think with version `2.1.x`?

**Comment by mantoni** [comment]
If this is still relevant, please open a new issue with a smaller example on how to reproduce. Closing.
