### ISSUE TITLE
Webdriver asynchronous behaviour is inconsistent using the API

### ISSUE THREAD

**Issue by eskatos** [mantoni/mochify.js#53]
Trying to use mochify from gulp I noticed that using `wd: true` leads to a different asynchronous behaviour than when using phantomjs or node.

Here is a sample project that show the issue: https://github.com/eskatos/gulp-mochify-attempt

gulp tasks:
- `test_node`
- `test_phantomjs`
- `test_wd`

The `test_wd` task return too soon, hence getting the test report in gulp not working.
This is different from `test_node` and `test_phantomjs` that just works.

Is there a callback somewhere that could be used to work around this?

Anyway, for the sake of the least surprise principle, I think this should be fixed.
WDYT?

**Comment by mantoni** [comment]
There was some refactoring lately regarding error handling and also in the webdriver module. This might have fixed the issue. @eskatos Can you check, please?

**Comment by eskatos** [comment]
Hey @mantoni, thanks for the feedback.
Unfortunately, for various reasons, I switched to other tools for the concerned project so won't be able to check.
