### ISSUE TITLE
Using API output stream

### ISSUE THREAD

**Issue by glassresistor** [mantoni/mochify.js#63]
I'm using 2.1 and trying to use the API instead of the cli.  I'm using it in grunt, we have to build templates and afew other things before we can run tests.
Its working in node but i looks like i need to use the output mentioned in docs so I can get grunt to output the results.  Do you have an example of using output?(i looked at the through2 docs but was a bit lost)

**Comment by ttamminen** [comment]
I think the documentation is a bit misleading.. 

> "Additional API options:

> output a stream that receives the test output (e.g. through2)"

But no mention about `.bundle` arguments.

**Comment by mantoni** [comment]
Yes. The documentation is missing a note that the browserify instance is returned. Thanks for pointing that out.

**Comment by mantoni** [comment]
@ttamminen Documentation adjusted according to your suggestion. Thanks.

**Comment by ttamminen** [comment]
Great, thanks! I am sure people will appreciate.
