### ISSUE TITLE
Passing --recursive option

### ISSUE THREAD

**Issue by DylanFM** [mantoni/mochify.js#68]
I can only find mention of Mocha's `--recursive` option in #17.
Just wondering how I can pass this option through to Mocha. Is it supported?
Thanks.

**Comment by mantoni** [comment]
It's not yet supported, but should be easy to put in.
Pull request welcome!

**Comment by DylanFM** [comment]
@mantoni I've begun working on a PR for this. It seems like these options (e.g `ui`, `reporter`) are being passed to mocaccino.js, rather than to Mocha. Support for the `recursive` option in mochify seems to depend on it being supported by mocaccino, and it appears that mocaccino doesn't support it. Let me know if this is correct, in which case I can look at putting together a PR for mocaccino too.

**Comment by mantoni** [comment]
Thanks for looking into this. Mocaccino is a Browserify plugin and does not resolve the files. You would want to modify the logic that resolves the entries that are passed to Browserify.
Here: https://github.com/mantoni/mochify.js/blob/master/lib/mochify.js#L25
and here: https://github.com/mantoni/mochify.js/blob/master/lib/mochify.js#L60

Maybe you could use a different default glob expression if `--recursive` is given.

**Comment by contra** [comment]
Next steps for this? Currently have my stuff pointed at this fork to use this feature

**Comment by DylanFM** [comment]
Apologies folks. I'm getting married this weekend, so have been focused on that. I intended to write the tests @mantoni suggested, and will end up doing so after our honeymoon finishes in mid-March.

**Comment by mantoni** [comment]
This has been released in `v2.6.0`.
