### ISSUE TITLE
Need to pass --web-security=[true|false] to phantomjs

### ISSUE THREAD

**Issue by krawaller** [mantoni/mochify.js#69]
Hey!
I'm building an api module that is supposed to work both in node and in privileged browser environments such as PhoneGap/Cordova. It contains integration tests making cross-origin requests to a url that is not CORS-enabled. This is fine for my use-case since the XHR in PhoneGap/Cordova is not restricted by the same-origin policy.

These integration tests work with mocha (since node too can make cross-origin requests), but fail in mochify since it's not currently possible to pass the necessary `--web-security=false` flag into mochify and on to phantomic and phantomjs. Do you think we could add support for it somehow? If so, I can do the implementation, but we'd of course have to agree on a sane solution.

I guess we could either make some kind of subargs thingy that lets you specify arbitrary arguments to be passed on from mochify to phantomic and then on to phantomjs, or we could add an explicit --web-security flag to mochify and phantomic. Do you prefer any of them, or do you have any other ideas?

Thanks!

**Comment by krawaller** [comment]
Oh, I realise this is very much related to https://github.com/mantoni/mochify.js/issues/26

**Comment by mantoni** [comment]
It should be straight forward to add an explicit -- option for this. Use the phantomjs option name and just pass it through.

I gave up looking into a generic solution for options. You need to know which one affects which library, assign default etc...

Thanks!

**Comment by krawaller** [comment]
@mantoni sweet!

I took a stab at it [here for mochify](https://github.com/mantoni/mochify.js/pull/71) and [here for phantomic](https://github.com/mantoni/phantomic/pull/7)!

**Comment by mantoni** [comment]
Good work :+1:
