### ISSUE TITLE
Maximum Call stack error

### ISSUE THREAD

**Issue by RongxinZhang** [mantoni/mochify.js#72]
![screen shot 2015-02-11 at 10 53 06 am](https://cloud.githubusercontent.com/assets/3782456/6153829/34c9789c-b1dc-11e4-9d48-1cc938ce8d20.png)

Please advice. 

@mantoni @jprichardson

**Comment by mantoni** [comment]
Please provide more context.

**Comment by mantoni** [comment]
If this is still relevant please open a new issue with more details including a description on how to reproduce it. Closing.
