### ISSUE TITLE
Exit code when used via api

### ISSUE THREAD

**Issue by mread** [mantoni/mochify.js#73]
We were hoping to see a non-zero exit code when we invoked mochify via its API, e.g.

```
var mochify = require('mochify');
mochify('broken-test-here.js').bundle();
```

Adding:
```
process.exit(1)
```
at line 77 of `mochify.js` fixed this.

Could you confirm that this is the right thing to do?

Thanks.

**Comment by mantoni** [comment]
If you're using the API you will have to call exit yourself. Browserifies `bundle` function accepts a callback (`cb(err, buf)`). Just do `if (err) process.exit(1);`.
