### ISSUE TITLE
Cannot generate code coverage when using Babelify transform

### ISSUE THREAD

**Issue by pheuter** [mantoni/mochify.js#74]
I am currently trying to leverage mochify to run tests and generate code coverage for my ES6 web app. The app uses [babelify](https://github.com/babel/babelify) to transform the ES6 JSX files.

I am currently able to successfully run the tests using mochify against the application like so:

```sh
$ mochify --transform babelify --reporter spec
```

The problem I am facing is when trying to generate code coverage. I have tried both with **coverify**:

```sh
$ mochify --transform babelify --cover
```

as well as with **mochify-istanbul**:

```sh
$ mochify --transform babelify --plugin [ mochify-istanbul --report cobertura ]
```

I get errors like:

```
Unexpected reserved word while parsing file: sample_component.jsx
```

```
node_modules/mochify/node_modules/coverify/bin/cmd.js:98
                        var rep = Array(b - a + 1).join('^');
                                  ^
RangeError: Invalid array length
    at node_modules/mochify/node_modules/coverify/bin/cmd.js:98:35
```

Any ideas?

**Comment by mantoni** [comment]
I would guess this is a coverify issue.
Can you try to creat a small (ideally a single file) example together to reproduce the issue?

**Comment by pheuter** [comment]
@mantoni Here is a sample **test/test.js** file, currently only spec in my test suite:

```js
import assert from "assert";

describe('Basic Test', () => {
  it("should understand ES6", () => {
    assert.equal(true, true);
  });
});
```

When I run the test suite, it works just fine:

```sh
$ mochify --transform babelify
```

However, when I run the coverage tool, it fails:

```sh
mochify --transform babelify --cover
```

with this error:

```
node_modules/coverify/bin/cmd.js:98
                        var rep = Array(b - a + 1).join('^');
                                  ^
RangeError: Invalid array length
    at node_modules/mochify/node_modules/coverify/bin/cmd.js:98:35
    at Array.forEach (native)
```

**Comment by mantoni** [comment]
Thanks. I tried to track it down and created an issue for Coverify.

**Comment by chromakode** [comment]
This was affecting me too. I've made a rough pass at implementing this here: https://github.com/substack/coverify/pull/17

Would appreciate a second (or third) pair of eyes!

**Comment by mantoni** [comment]
Thanks for that. This was released before I even had a chance to look at it. Having a quick release cycle now allows everyone to play with it and report more issues :+1:

**Comment by Swaagie** [comment]
This only fixed a part of the issue, I can confirm `--cover` works, but the mochify-instanbul plugin does not support reactify/babelify, unless I overlooked something :)

**Comment by mantoni** [comment]
Thanks for reporting. For the mochify-istanbul plugin, please file an issue in for [that project](https://github.com/ferlores/mochify-istanbul/issues).

Re passing parameters to coverify: No, this is not yet supported. There is a refactoring being planned to move things into separate plugins. That would then support all options.

In the meantime, try modifying your first line like this:

```
mochify -R spec --node --transform reactify --transform [ coverify --json --output coverage.json ] ./test/*test.js | coverify
```

It is important to use a reporter that works line by line for coverify to work like this. Mochify has some special stream filter logic to make it work with all the reporters.

**Comment by Swaagie** [comment]
Thanks for the quick reply, note that the options still should be appended to the final coverify for them to work. 

```
mochify --node --transform reactify --transform coverify ./test/*test.js | coverify --json --output coverage.json
``` 

Sadly substack hates on lcov (for some reason) and piping the JSON to lcov will be a no go ;)

**Comment by Swaagie** [comment]
For future references, generating coverage with mochify-istanbul is already possible. You will need this fix https://github.com/ferlores/mochify-istanbul/pull/13 for multiple file support though. Hopefully that will be merged soon. Simply add mochify-istanbul as plugin

```
mochify(/* ... */)
  .plugin(require('mochify-istanbul), {
    exclude: ['**/test/**/*', '**/node_modules/**/*']
    report: ['text', 'cobertura', 'json'],
    dir: './coverage'
  })
```

**Comment by mantoni** [comment]
@Swaagie Thanks for the update.
