### ISSUE TITLE
Use `paths` browserify option with mochify

### ISSUE THREAD

**Issue by gryzzly** [mantoni/mochify.js#76]
Hey! 

I'm using the following in the browserify config: 
```js
browserify(
  entries: src + '/scripts/Main.js',
  dest: dest + '/js',
  outputName: 'Main.js',
  paths: ['./app/scripts/']
)
```

And I use the following in mochify config:
```js
mochify('./test/**/*.js', {
    reporter : 'spec',
    paths: ['./app/scripts/']
})
```

However, the `paths` option doesn't seem to be picked up. How can I pass browserify option to browserify? 

Thanks!

**Comment by mantoni** [comment]
Thanks for reporting this. This option isn't supported yet. Should be easy to add. Care to look into it?

**Comment by gryzzly** [comment]
@mantoni thanks for the prompt reply. Not *urgent* for me right now, so I'll try to look into it over next couple of days.

**Comment by mantoni** [comment]
I just had a look at this and noticed that the `paths` option is not in the Browserify API documentation. If it's not an officially supported option, I would rather not add it to Mochify. What do you think?

**Comment by wjordan** [comment]
The browserify maintainer [strongly recommends against](http://stackoverflow.com/a/25296734) using the `paths` option:
> that approach is a deprecated part of the module system in node and browserify, so it could stop working at any time.

Instead of adding entries to `paths`, the recommended approach looks to be adding a symlink in `./node_modules/` pointing to any local modules you want to reference without using relative requires.

**Comment by mantoni** [comment]
Thanks for the clarification @wjordan

**Comment by wjordan** [comment]
Slight update- it looks like the `paths` option was just now added to the Browserify documentation (see PR [#1167](https://github.com/substack/node-browserify/pull/1167)), so I guess it's no longer considered to be deprecated/unsupported. Here's the added text:

> `opts.paths` is an array of directories that browserify searches when looking
for modules which are not referenced using relative path. Can be absolute or
relative to `basedir`. Equivalent of setting `NODE_PATH` environmental variable
when calling `browserify` command.

**Comment by mantoni** [comment]
Cool. Reopening. PR welcome in that case :)

**Comment by mantoni** [comment]
The `paths` config and the corresponding `--path` command line switch where just introduced in the fresh `2.17.0` release.
