### ISSUE TITLE
Question: how to serve local file for testing?

### ISSUE THREAD

**Issue by fluffynukeit** [mantoni/mochify.js#79]
I am writing a [typeset](https://github.com/fluffynukeit/jMatFile) for [jbinary](https://github.com/jDataView/jBinary).  I wrote lots of tests with mocha/chai that read local test files on my system, parse, and validate.  These run great when running with mocha and node.

Because of some node limitations and because I intend for this typeset to be used primarily in the browser, I want to migrate the tests to the browser.  Mochify seems like an easy tool for that.  However, I am having problems reading the test files in order to run the tests.  I've tried file URLs, `--port xxxxxx`, http requests to localhost:xxxxxx, and messing with the web-security flag, phantomjs debug mode, etc.  

It seems like there are a lot of parts that need to align in order to do this - too many for me to exhaustively try.  What do I need to do in order for my mocha tests to read a test file I have on my local file system when using mochify?  Any tips much appreciated!

**Comment by mantoni** [comment]
You could inline your resource files into the tests with brfs: https://www.npmjs.com/package/brfs

If the resources are json files, you don't even need brfs. You can simply `require` them and browserify will add the json to the bundle.

Hope this helps.

**Comment by fluffynukeit** [comment]
Thank you for the response.  I looked into brfs previously and it seemed not up to the task because the files are 10 MB binary files, not json or any text format.  I'll review it more closely again.

Does mochify have no capability to serve files?  In other words, am I trying to do something that's not possible?

**Comment by mantoni** [comment]
At least it seems you are trying to do something that it's not intended to do. Nothing stops you from forking an http server yourself and use the Mochify API. But the original intention was to run unit tests abd not integration tests.

Having said that, I am thinking of adding more capabilities for integration style test cases. I'd like to be able to specify a URL to load and then inject the test cases into the web page. That would still not include any http serving application though. I would prefer to keep this outside of Mochify.

If you have any other ideas, I'm all ears.

**Comment by fluffynukeit** [comment]
Thanks.  I was confused because I thought mochify had some http serving capability because of the available options.  I will look for a different solution first, then revisit the mochify API if it seems like the right way to go.

I realize my case is a special case, but I am intending for it to be used as unit tests.  But since I'm testing a binary parser, I need data to test against.

In any event, thanks for mochify!  Tremendously useful.

**Comment by fluffynukeit** [comment]
Just wanted to confirm that this is the right syntax for invoking brfs with mochify. TYVM.

```
mochify --consolify mytest.html --transform brfs
```

**Comment by mantoni** [comment]
Yes, that is how it works. Alternatively, you can soecify the transform in your package.json: https://github.com/substack/browserify-handbook/blob/master/readme.markdown#browserifytransform-field
