### ISSUE TITLE
Broken module, broken tests

### ISSUE THREAD

**Issue by ferlores** [mantoni/mochify.js#80]
Hi @mantoni 
I just realized that if you delete your `node_module` folder and `npm install` the dependencies again mochify doesn't report back the result of the tests run in phantom. It looks like a dependency got broken.

I discover this through one of the projects where I use mochify, and I confirmed it by cloning the repo from scratch, ```npm install``` and run the tests. Half of them fail.

Do you mind looking at it? 

Thanks!
F

**Comment by mantoni** [comment]
Thanks for the heads up. Will look into it as soon as I get near a computer.

-Max

**Comment by tjunghans** [comment]
I noticed the same issue. I don't see any test results. The only output is `#phantomjs:`. I'm using phantomjs v1.9.7 and mochify v2.7.0.

**Comment by mantoni** [comment]
This was introduce in [browserify 9.0.4](https://github.com/substack/node-browserify/pull/1187). As a quick fix, I'll nail browserify to `9.0.3`.

Apparently, streams that are pushed to `pipeling.get('wrap')` are not part of the output stream anymore. E.g. inserting `n.stdout.pipe(process.stdout);` [at this line](https://github.com/mantoni/mochify.js/blob/master/lib/node.js#L39) shows the expected output on the console.

 If anybody can look further into this, I'd be very thankful.

**Comment by mantoni** [comment]
Worked around in Mochify `v2.7.1`. Please re-install. I'll keep this issue open until there is a proper solution.

**Comment by mantoni** [comment]
I still don't understand the issue 100%, but `v2.7.2` has a "good enough" workaround.
