### ISSUE TITLE
Serve Local JSON

### ISSUE THREAD

**Issue by gregorskii** [mantoni/mochify.js#84]
Hi there,

I have a particular use case whereby my tests need to access a local URL to grab some JSON fixture data. Is it possible to serve a path of local assets with the bundle that runs with the test?

Thanks

**Comment by mantoni** [comment]
Have a look at brfs, maybe that solves it for you?
https://github.com/substack/brfs

**Comment by gregorskii** [comment]
Hmm, it would need to serve them as the same path using a GET command. The code is calling $.ajax or backbone model.fetch to get the data. I believe brfs would require me in the module to override the AJAX and respond with the brfs fs.readFile. I am trying to test the models/collections without having to fundamentally change their code.

What do you think?

**Comment by mantoni** [comment]
Use http://sinonjs.org fake server?

**Comment by gregorskii** [comment]
Yes. Most likely doing this wrong. Will look into Sinon. Thanks!
