### ISSUE TITLE
phantomjs api option not working

### ISSUE THREAD

**Issue by jxm262** [mantoni/mochify.js#90]
I'm trying to set phantomjs directly with the api, but it doesn't seem to work with a local phantomjs installation.  
  
Perhaps I have the syntax wrong?  
```    
//local installation
var phantomjs = require('phantomjs');

mochify('./test/site/js/**/*.js', {
    transform: ['reactify'],
    reporter: 'spec',
    phantomjs: phantomjs
})
.bundle();
```  

However, It seems to work with the command line option `--phantomjs`, but I need to use the API.

**Comment by jxm262** [comment]
Ok, looks like I didn't understand the api correctly.  It takes the actual path of the phantomjs installation.  The following is working now..

```
//local installation
var phantomjs = require('phantomjs');

mochify('./test/site/js/**/*.js', {
    transform: ['reactify'],
    reporter: 'spec',
    phantomjs: './node_modules/phantomjs/bin/phantomjs'
})
.bundle();
```
  
Would it make more sense to have the phantomjs api option accept directly from the required package (ie. like i have in the above thread)?

**Comment by mantoni** [comment]
If that's your use case, make it a pull request. The `phantomjs` option could accept both, depending on the type maybe?

**Comment by jxm262** [comment]
Sure, I'll make a PR.  Let me know if you think this wouldn't be useful, but I think it makes sense to do it to allow the option.

**Comment by mantoni** [comment]
Looks reasonable from your code snipped above. There seem to be quite a few people who use the phantomjs npm module. Go ahead!

**Comment by jxm262** [comment]
@mantoni  so after looking at this, I kind of agree more with the previous ticket that phantom should come prebundled with mochify  https://github.com/mantoni/mochify.js/issues/28  
I think this would help clear alot of confusion.  Couple reasons I think this would be good.  
  
+ makes 1 less touch point for the developer to include manually  
+ follows the same logic your currently doing for other modules
  * (ex: you're already including mocha, browserify, etc..)  
+ keeps the mochify project more in sync with any version inconsistencies.  For example if phantomjs ever gets updated and breaks something in the mochify project.  
+ you can still very easily keep the existing mochify option parameter as-is to allow users to override the one that would be preinstalled.  
+ Would play nicely with your [phantomic](https://github.com/mantoni/phantomic) module since we just need to pass in the directory of the preinstalled module (minimal code changes on mochify)
  
I would also think you wouldn't want to use a global module (I personally very much try to limit my usages of global modules), since the project is dependent on it.  
  
[example discussion here](http://blog.nodejs.org/2011/03/23/npm-1-0-global-vs-local-installation)  
  
>In general, the rule of thumb is:
>1.) If you’re installing something that you want to use in your program, using require('whatever'), then install it locally, at the root of your project.  
  
If you think this is a decent idea, I can submit a PR for this.  
  
Let me know!

**Comment by mantoni** [comment]
Yes, your arguments are absolutely valid. I do like the idea in general. Like I explained maybe not very well in #28 I don’t want go for the dependency because it doesn’t recognize my existing PhantomJS install. It doesn’t matter whether PhantomJS was installed via npm globally or whether I used some other way of putting the binary into my PATH. It always downloads this really large binary from bitbucket. I use Mochify extensively at work for more than 150 modules. We run fresh installs on each build and we have a company proxy that blocks all traffic to bitbucket. I don’t want to configure the path to the PhantomJS binary into each of the projects. They even have to run on different platforms. I already have the correct PhantomJS binary in my PATH. Everybody in the team does. That’s really the only problem. As soon as the phantomjs npm module detects and uses my existing binary, I’m all for it. Until then, I’m not going to add it as a dependency.

If you have any suggestions on how to work around this problem, I’m all ears.

**Comment by jxm262** [comment]
ahhh... ok just took a look at the filesize for phantomjs and it's pretty huge.  I see your line of reasoning now.  
  
Let me think about this a bit.  I think there's a couple ideas to accomplish this but want to think about the best way to architect it.

**Comment by ljharb** [comment]
That's what `peerDependencies` or `optionalDependencies` are for. If your code needs it, it **must** be listed somewhere in `package.json` imo.

**Comment by mantoni** [comment]
@ljharb `peerDependencies` are deprecated and `optionalDependencies` are allowed to fail, but it would still try and download the whole thing every time. I'm not adding phantomjs as any kind of dependency ever unless it does not download the binary if I already have it installed.

**Comment by ljharb** [comment]
It won't. `npm` will have it cached locally (likely in `~/.npm`) if you've already `npm install`ed that version, whether globally or locally - so this is a non-concern.

The reality is that anything that your node program requires to run must be a dependency in `package.json`, or else your program is broken.

**Comment by mantoni** [comment]
It won't load the phantoms dependency, but the phantomjs module itself downloads the phantomjs binary from bitbucket, like I explained above.

**Comment by ljharb** [comment]
ah, i missed that. In that case that's a hugely awful bug in phantom itself :-) has it been filed with them?

**Comment by mantoni** [comment]
Dunno. Go ahead and file it :)

**Comment by jxm262** [comment]
I'm looking into this currently and will probably file a bug after I play around with it a bit more.  See this related SO post on phantom http://stackoverflow.com/questions/28418957/phantomjs-npm-is-installing-locally-even-if-same-version-is-on-global  
  
Will report back soon with an update to this ticket

**Comment by mantoni** [comment]
Cool :+1:

**Comment by boneskull** [comment]
you could write a little `prepublish` script that does something like:

- try to `npm link` phantomjs
- if that succeeds, great, you're done.
- if that fails, `npm install` it.

**Comment by boneskull** [comment]
(let me know if you're interested in this solution; I've used something similar in my own packages)

**Comment by mantoni** [comment]
That sounds like a good solution. However, that wouldn't find phantomjs in the `PATH`, right?

**Comment by boneskull** [comment]
@mantoni did you `npm install -g phantomjs`?

**Comment by mantoni** [comment]
Yes, on Mac I did. On the Linux VM at work, I think I installed phantomjs from an rpm. Maybe we can use your idea with the script and also check if `which phantomjs` exists with `0`?

**Comment by boneskull** [comment]
if you `npm install -g phantomjs` then the link will work

**Comment by boneskull** [comment]
sorry, i mean we won't need to look in the path, since it will be in the path.

**Comment by mantoni** [comment]
Yes, I know. But if `phantomjs` is already in the path and it was not installed through npm, like on travis, then there is no need to install it either.

**Comment by boneskull** [comment]
@mantoni Is that necessary--a common use case?  If you'd like this, I could throw it in, I suppose, but it may require depending on [which](https://www.npmjs.com/package/which) for cross-platform support.

**Comment by mantoni** [comment]
I would prefer a solution that finds any installed binary. Using `which` sounds good because it will also find a global npm link. :+1:
