### ISSUE TITLE
Piping to out only breaks phantomJS

### ISSUE THREAD

**Issue by Swaagie** [mantoni/mochify.js#93]
Running mochify with basic options using phantomJS and browserify ~9.0.7, this change https://github.com/mantoni/mochify.js/commit/f221e5576ef551934ed60c1473948cfc0dd77b80 will just leave phantomJS dead in the water. Reverting the change will make it work again, perhaps pipe to both streams to make sure watch works?

**Comment by Swaagie** [comment]
Excluded outdated browserify being the issue

**Comment by mantoni** [comment]
Just released `v2.10.0` which now uses browserify 10. Can you check if this is still an issue? I can't reproduce.

If you still have this issue, please post the node and phantomjs versions you're using and how you're using Mochify (command line / API).
