### ISSUE TITLE
Timeout issues with mochify@2.10.0. 2.9.0 works fine.

### ISSUE THREAD

**Issue by tjunghans** [mantoni/mochify.js#94]
A large amount of test cases or complicated tests are causing the test-run to timeout with mochify@2.10.0. A **downgrade to 2.9.0 fixes the issue**.

In one case the tests running locally timeout with the following exception:
`timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.`

In another case selenium was reporting timeouts. The timeout can be reproduced reliably, however the number of test cases that run before the time out varies.

**Comment by mantoni** [comment]
Can you isolate the issue into something reproducible?

**Comment by tjunghans** [comment]
Sure, I'll try to whip something up.

**Comment by tjunghans** [comment]
The error has no correlation with the number of test cases (it-statements) or assertions. There's also no correlation with the duration of the test-run. A dummy test-run with a duration of over 6 minutes, 100k it-statements doing DOM manipulation were no problem. The problem lies somewhere else. Still analyzing...

**Comment by mantoni** [comment]
So it turns out to be `process.nextTick` that needs to be stubbed away. It's the one potentially breaking change in Browserify 10 that was causing the issue.
See https://github.com/substack/node-browserify/blob/master/changelog.markdown#1000
Closing.
