### ISSUE TITLE
How to bundle all test JS files into a single JS file?

### ISSUE THREAD

**Issue by coppercash** [mantoni/mochify.js#96]
Hi,

I develop on iOS and Android. I want to test if my node-flavored JS project works on them.

So I need to bundle all my `*.test.js` and their dependencies into a `test_bundle.js`, just as I usually do with `Browserify`.

Can I achieve that with `Mochify`? I tried `.bundle()`, but it returned me a test report.

Thanks

**Comment by mantoni** [comment]
You can use the `--consolify` option to export a web page that runs the tests. You can specify an external bundle file with `--bundle` if you need one. Either open the web page on the device or do something else with the bundle file.

Let me know if that works for you.

**Comment by coppercash** [comment]
How silly I was. I should read README carefully first.

Another thing is that do you think I can pipe the test results to Xcode's console?

I looked into the `output.js` which I get from `--bundle`. And find if I can replace function `appendLine` with a native ObjC block (which can be achieved after iOS 7), then the `msg` string can be passed to `NSLog`.The only problem here is, the tests start just after the `output.js` loaded. I have no chance to replace it.

**Comment by mantoni** [comment]
Oh wow, I don't know. I start to believe that you're better off using the underlying plugins directly with browserify, like mocaccino.

**Comment by coppercash** [comment]
Really appreciate your help. I will figure that out myself maybe.

**Comment by mantoni** [comment]
Have a look at the [mocaccino readme](https://www.npmjs.com/package/mocaccino). I think that explains what you actually need.
