### ISSUE TITLE
change viewport size in tests

### ISSUE THREAD

**Issue by balaclark** [mantoni/mochify.js#97]
Is there currently a way to get to the phantomjs page in order to change the `viewportSize` (http://phantomjs.org/api/webpage/property/viewport-size.html) before running tests? This would enable responsive code to be tested.

**Comment by mantoni** [comment]
No, that's not yet implemented. I'd accept a PR on [phantomic](https://github.com/mantoni/phantomic) and a corresponding one here.

**Comment by m90** [comment]
This feature is now available in `mochify@3.2.1`, you can use `--viewport-height` and `--viewport-width` to pass values.
