### ISSUE TITLE
requiring nock library fails when using mochify to run test

### ISSUE THREAD

**Issue by m90** [mantoni/mochify.js#99]
I would like to use `nock` (https://github.com/pgte/nock) to mock server responses in a test run by mochify.

Yet requiring the library
```js
var nock = require('nock');
```
will throw
```
# phantomjs:
TypeError: 'undefined' is not an object (evaluating 'superCtor.prototype')
      at node_modules/inherits/inherits_browser.js:5
      at node_modules/nock/lib/intercept.js:266
      at null:null
      at node_modules/nock/lib/recorder.js:6
      at null:null
      at node_modules/nock/index.js:1
      at test/parser.js:4
      at null:null
```
The same install will work fine when using mocha.

I am completely stumped where this might stem from and if it is an issue with mochify, nock or phantomjs.

Used versions are:
```
    "mochify": "^2.10.0",
    "nock": "^2.7.0",
```

Sorry if this might be the wrong place to post this issue, but I simply have no clue what the problem is here.

**Comment by mantoni** [comment]
Can you post a small piece of code that reproduces the issue?

**Comment by m90** [comment]
Sure thing: https://github.com/m90/mochify-nock-issue

Thanks!

**Comment by mantoni** [comment]
Thanks! Are you sure that `nock` supports running in a browser?

I will only be able to investigate further on Monday as I don't have accesss to a computer this weekend.

**Comment by m90** [comment]
That's a very interesting question that I haven't really been thinking about until now :goat: 

The docs says nothing about browsers and if they're supported or not, only

> Nock is an HTTP mocking and expectations library for Node.js

Do you know of a HTTP mocking library that works well with mochify?

No need to rush.

**Comment by mantoni** [comment]
Sure. Have a look at [Sinon.JS](http://sinonjs.org). It has a very good [fake server](http://sinonjs.org/docs/#fakeServer) implementation – and I contribute there myself :-)

**Comment by m90** [comment]
Ok great, I'm using it already!

I also found this: https://github.com/pgte/nock/issues/150 which is basically the exact same issue, so it looks like it's *not yet* supported.

Thanks for all the hints as well as your library!

**Comment by mantoni** [comment]
:+1:
